###ADMIN CREATE USER
POST http://localhost:8081/profile/adm/create/student
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBQTIwMDQwOTIiLCJpYXQiOjE2NTk3MzE2MDEsImV4cCI6MTY1OTgxODAwMSwiaXNzIjoibWF6Z2kgcHJvZHVjdGlvbiJ9.YYo5LefQIgmeQWjBfX5gphrXbBVxZ50Ja6mVrN-vuL4

{
  "faculty": "Asuu",
  "groups": "202",
  "login": "AA7643333",
  "password": "passwordd",
  "surname": "Aziza",
  "name": "Abdulla",
  "phone": "+998990340000"
}

###STATUSNI OZGARTIRISH
PUT http://localhost:8081/profile/adm/change_status/0000000082829616018286
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBQTIwMDQwOTIiLCJpYXQiOjE2NjUzNDE4OTUsImV4cCI6MTY2NTQyODI5NSwiaXNzIjoibWF6Z2kgcHJvZHVjdGlvbiJ9.LO5aFI4E45NucaNufXddoDu_GQBKZ_N8NEK3NqKwL2o



###LOGIN BOYICHA QIDIRSH
GET http://localhost:8081/profile/public/full_info/AA2004092
Content-Type: application/json


###UMUMIY USERLAR
POST http://localhost:8081/profile/adm/profile_list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBQTIwMDQwOTIiLCJpYXQiOjE2NjUzNDE4OTUsImV4cCI6MTY2NTQyODI5NSwiaXNzIjoibWF6Z2kgcHJvZHVjdGlvbiJ9.LO5aFI4E45NucaNufXddoDu_GQBKZ_N8NEK3NqKwL2o

###BLOCK USERLAR
POST http://localhost:8081/profile/adm/profile_list/status/block
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBQTIwMDQwOTIiLCJpYXQiOjE2NjUzNDE4OTUsImV4cCI6MTY2NTQyODI5NSwiaXNzIjoibWF6Z2kgcHJvZHVjdGlvbiJ9.LO5aFI4E45NucaNufXddoDu_GQBKZ_N8NEK3NqKwL2o



###ACTIVE USERLAR
POST http://localhost:8081/profile/adm/profile_list/status/active
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBQTIwMDQwOTIiLCJpYXQiOjE2NTk3MzA0MTQsImV4cCI6MTY1OTgxNjgxNCwiaXNzIjoibWF6Z2kgcHJvZHVjdGlvbiJ9.skZgDRGqquIFFwvUT551WXPbQkvn0IVYmC7grPhQVds